### ISSUE TITLE
The game crashes when the level spawned around four vegetables (and among other things).

### ISSUE THREAD

**Issue by Raccoon-JS** [pigdevstudio/kitchen-tales#71]
Oink oink. Here is the latest issue while testing the game.

- **The game crashes when the level spawned more than four vegetables**.
![Spawner_bug](https://user-images.githubusercontent.com/51072029/69084066-58f4ae00-0a3b-11ea-8939-530bdec3231e.png)
  - **This is the error message I got**:
```
E 0:00:28:0358   Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead
  <C Source>     servers/physics_2d/physics_2d_server_sw.cpp:416 @ area_set_shape_disabled()
  <Stack Trace>  Spawner.gd:8 @ spawn()
                 Attack.gd:15 @ execute()
                 State.gd:68 @ execute()
                 StateMachine.gd:59 @ execute()
                 Brain.gd:40 @ _on_CombateStateMachine_state_changed()
                 StateMachine.gd:49 @ change_state_to()
                 StateMachine.gd:49 @ change_state_to()
                 HurtBox.gd:12 @ get_hurt()
                 HurtBox.gd:19 @ _on_area_shape_entered()
```
- When I am controlling Buccerino, he sometimes moonwalk or just go autopilot.
- The onion just froze after emmitting gas.
![OnionStopped](https://user-images.githubusercontent.com/51072029/69084113-745fb900-0a3b-11ea-8c9b-13e39e8d662e.png)
- Received Stack Frames error notice in Gravity.gd.
![Gravity_bug](https://user-images.githubusercontent.com/51072029/69084125-7a559a00-0a3b-11ea-8268-428a3ce1163b.png)

**Comment by henriiquecampos** [comment]
> The game crashes when the level spawned around four vegetables

Can you replicate this somehow @Raccoon-JS ? I think it has to do with something else other than just getting a fourth spawn, I mean yeah the fourth spawn can trigger a crash, but due to something else. I need to investigate this.

**Comment by Raccoon-JS** [comment]
I just pulled your latest commit, and now the Onions and Tomatoes aren't spawning anymore. The Carrot is still spawning, but only in one location. And I still receive this same error:
```
E 0:00:48:0795   Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead
  <C Source>     servers/physics_2d/physics_2d_server_sw.cpp:416 @ area_set_shape_disabled()
  <Stack Trace>  Spawner.gd:8 @ spawn()
                 Attack.gd:15 @ execute()
                 State.gd:68 @ execute()
                 StateMachine.gd:59 @ execute()
                 Brain.gd:40 @ _on_CombateStateMachine_state_changed()
                 StateMachine.gd:49 @ change_state_to()
                 StateMachine.gd:49 @ change_state_to()
                 HurtBox.gd:12 @ get_hurt()
                 HurtBox.gd:19 @ _on_area_shape_entered()
```
