### ISSUE TITLE
Onion Freezes on spawn or after spawning a gas cloud

### ISSUE THREAD

**Issue by henriiquecampos** [pigdevstudio/kitchen-tales#73]
As mentioned by @Raccoon-JS in #71, the Onion is stucked after emitting a gas cloud and even after being spawned.

**Comment by Raccoon-JS** [comment]
And I would like to mention that one of the GasCloud the Onion spewed doesn't fade out.

**Comment by henriiquecampos** [comment]
This is fixed on b527a69f969ce75bd65a607729ed3a62d84f5a6a and it happens due to NodePaths exported to the inspector.

Their paths were pointing to an absolute "Onion" path, so if there was 2 Onions, the second one would be pointing to the first one. I dunno why this happened tho, but the fix was to clean the overriding path (the scripts' default is relative already).

It will be closed as soon as I merge b527a69f969ce75bd65a607729ed3a62d84f5a6a into master, you can try it out on [demo-bring-17](https://github.com/pigdevstudio/kitchen-tales/compare/demo-bring-17) branch
